name: scanalyst
base: core22 # the base snap is the execution environment for this snap
version: '0.0.1'
summary: Static (java) code analysis with SonarQube # 79 char long summary
description: |
  This application analyses the code quality of the .java files in a git repository.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  runner:
    plugin: dump
    source: .
    override-build: |
      craftctl default
      chmod +x runner/run.sh


apps:
  scanalyst:
    command: ./runner/run.sh